SSB.Dictionnary = {["Destructive Touch"] = "Destructive Touch",["Destructive Clench"] = "Destructive Clench",["Destructive Reach"] = "Destructive Reach",["Wall of Elements"] = "Wall of Elements",["Unstable Wall of Elements"] = "Unstable Wall of Elements",["Elemental Blockade"] = "Elemental Blockade",["Force Shock"] = "Force Shock",["Crushing Shock"] = "Crushing Shock",["Force Pulse"] = "Force Pulse",["Weakness to Elements"] = "Weakness to Elements",["Elemental Susceptibility"] = "Elemental Susceptibility",["Elemental Drain"] = "Elemental Drain",["Impulse"] = "Impulse",["Elemental Ring"] = "Elemental Ring",["Pulsar"] = "Pulsar",["Fire Touch"] = "Destructive Touch",["Fire Clench"] = "Destructive Clench",["Fire Reach"] = "Destructive Reach",["Wall of Fire"] = "Wall of Fire",["Unstable Wall of Fire"] = "Unstable Wall of Fire",["Blockade of Fire"] = "Elemental Blockade",["Force Shock"] = "Force Shock",["Crushing Shock"] = "Crushing Shock",["Force Pulse"] = "Force Pulse",["Weakness to Elements"] = "Weakness to Elements",["Elemental Susceptibility"] = "Elemental Susceptibility",["Elemental Drain"] = "Elemental Drain",["Impulse"] = "Impulse",["Fire Ring"] = "Elemental Ring",["Fiery Pulsar"] = "Pulsar",["Frost Touch"] = "Destructive Touch",["Frost Clench"] = "Destructive Clench",["Frost Reach"] = "Destructive Reach",["Wall of Frost"] = "Wall of Elements",["Unstable Wall of Frost"] = "Unstable Wall of Elements",["Blockade of Frost"] = "Elemental Blockade",["Force Shock"] = "Force Shock",["Crushing Shock"] = "Crushing Shock",["Force Pulse"] = "Force Pulse",["Weakness to Elements"] = "Weakness to Elements",["Elemental Susceptibility"] = "Elemental Susceptibility",["Elemental Drain"] = "Elemental Drain",["Frost Impulse"] = "Impulse",["Frost Ring"] = "Elemental Ring",["Frost Pulsar"] = "Pulsar",["Shock Touch"] = "Destructive Touch",["Shock Clench"] = "Destructive Clench",["Shock Reach"] = "Destructive Reach",["Wall of Storms"] = "Wall of Storms",["Unstable Wall of Storms"] = "Unstable Wall of Elements",["Blockade of Storms"] = "Elemental Blockade",["Force Shock"] = "Force Shock",["Crushing Shock"] = "Crushing Shock",["Force Pulse"] = "Force Pulse",["Weakness to Elements"] = "Weakness to Elements",["Elemental Susceptibility"] = "Elemental Susceptibility",["Elemental Drain"] = "Elemental Drain",["Shock Impulse"] = "Impulse",["Lightning Ring"] = "Elemental Ring",["Electric Pulsar"] = "Pulsar"}
SSB.Textures = {
	["/esoui/art/icons/ability_destructionstaff_005.dds"] = "/esoui/art/icons/ability_destructionstaff_005.dds",
	["/esoui/art/icons/ability_destructionstaff_002.dds"] = "/esoui/art/icons/ability_destructionstaff_002.dds",
	["/esoui/art/icons/ability_destructionstaff_008.dds"] = "/esoui/art/icons/ability_destructionstaff_008.dds",
	["/esoui/art/icons/ability_destructionstaff_007.dds"] = "/esoui/art/icons/ability_destructionstaff_005.dds",
	["/esoui/art/icons/ability_destructionstaff_004.dds"] = "/esoui/art/icons/ability_destructionstaff_002.dds",
	["/esoui/art/icons/ability_destructionstaff_010.dds"] = "/esoui/art/icons/ability_destructionstaff_008.dds",
	["/esoui/art/icons/ability_destructionstaff_006.dds"] = "/esoui/art/icons/ability_destructionstaff_005.dds",
	["/esoui/art/icons/ability_destructionstaff_003.dds"] = "/esoui/art/icons/ability_destructionstaff_002.dds",
	["/esoui/art/icons/ability_destructionstaff_009.dds"] = "/esoui/art/icons/ability_destructionstaff_008.dds"
}